#!/usr/bin/env ruby
irb = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'
 
libs =  " -r irb/completion"
libs <<  " -r #{File.join(File.dirname(__FILE__), '../config/boot.rb')}"

puts "Loading Godwit Environment..."
exec "#{irb} #{libs} --simple-prompt"